version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/kubecrsh
    binary: kubecrsh
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

dockers:
  - id: ghcr-stable
    skip_push: "{{ if .Prerelease }}true{{ else }}false{{ end }}"
    image_templates:
      - "ghcr.io/kadirbelkuyu/kubecrsh:{{ .Tag }}"
      - "ghcr.io/kadirbelkuyu/kubecrsh:v{{ .Major }}"
      - "ghcr.io/kadirbelkuyu/kubecrsh:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/kadirbelkuyu/kubecrsh:latest"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - id: ghcr-prerelease
    skip_push: "{{ if .Prerelease }}false{{ else }}true{{ end }}"
    image_templates:
      - "ghcr.io/kadirbelkuyu/kubecrsh:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

release:
  github:
    owner: kadirbelkuyu
    name: kubecrsh
  draft: false
  prerelease: auto
  make_latest: "{{ if .Prerelease }}false{{ else }}true{{ end }}"
