apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecrsh-config
  namespace: kubecrsh
data:
  config.yaml: |
    namespace: kubecrsh
    reports:
      path: /data/reports
      retention: 168h
    watch:
      reasons:
        - OOMKilled
        - Error
        - CrashLoopBackOff
    leader_election:
      enabled: false
      lease_name: kubecrsh-leader-election
      lease_duration: 15s
      renew_deadline: 10s
      retry_period: 2s
    elasticsearch:
      enabled: false
      addresses:
        - http://elasticsearch:9200
      index: kubecrsh-reports
